### PR TITLE
Update Arrow to arrow-one-mmap-file-on-b228489

### PR DESCRIPTION
**Pull request by guoyuhong**
Described here: https://github.com/ray-project/ray/pull/4127#issuecomment-466313215

### CODE REVIEW

**Comment by pcmoritz** [comment]
@guoyuhong Thanks for the patch! Now that https://github.com/ray-project/ray/pull/3898 is merged, we can move forward with this.

Before we can merge it, however we first need to fix the problem https://issues.apache.org/jira/browse/ARROW-4491 that happens with newer versions of arrow. If you have spare capacity to look into this let me know! I can only get to it at the end of the week I think, as I'm currently busy with https://github.com/ray-project/ray/issues/4129, which I'm prioritizing to make sure we can exit the stage where we have to support both CMake and Bazel as soon as possible.

**Comment by guoyuhong** [comment]
@pcmoritz Thanks for the information. I'm not quite understand what the Arrow JIRA issue is about. If I have time in the next several days, I will take a look at that issue.

**Comment by guoyuhong** [comment]
@pcmoritz I have merged https://github.com/apache/arrow/pull/3758 . Is that the correct solution?

**Comment by pcmoritz** [comment]
Thanks, yes that is working now! Great :)

This PR is now integrated into the master of this repo too!

**Pull request closed without merging**
